apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefikee
resources:
- namespace.yaml
- configmap-teectl.yaml
- configmap-static-config.yaml
- secret-example-license.yaml
- secret-aws-env.yaml
- rbac-teectl.yaml
- job-init-teectl-config.yaml
- job-teectl-create-plugin.yaml
- release.yaml

